LOGIN = "ysabr"
SERVER_NAME = "#{LOGIN}S"
SERVER_IP = "192.168.56.110"
WORKER_NAME = "#{LOGIN}SW"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.name = "p1-#{SERVER_NAME}"
    end

    server.vm.provision "shell",
      path: "scripts/Server.sh",
      env: {
        "SERVER_IP" => SERVER_IP,
        "NODE_IP" => SERVER_IP
      }
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network "private_network", ip: WORKER_IP

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "p1-#{WORKER_NAME}"
    end

    worker.vm.provision "shell",
      path: "scripts/ServerWorker.sh",
      env: {
        "SERVER_IP" => SERVER_IP,
        "WORKER_IP" => WORKER_IP,
        "NODE_IP" => WORKER_IP
      }
  end
end
