Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.hostname = "ysabr-bonus"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ysabr-bonus"
    vb.memory = 6144
    vb.cpus = 4
  end

  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8181, host: 8181

  config.vm.provision "shell", path: "./scripts/installation.sh", name: "installation"
  config.vm.provision "shell", path: "./scripts/setup.sh", name: "setup"
  config.vm.provision "shell", path: "./scripts/port-forwarding.sh", name: "port-forwarding", run: "always"
end
