Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.hostname = "ysabr-p3"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ysabr-p3"
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provision "shell", path: "./scripts/installation.sh", name: "installation"
  config.vm.provision "shell", path: "./scripts/setup.sh", name: "setup"
  config.vm.provision "shell", path: "./scripts/port-forward.sh", name: "port", run: "always"
end
